name: Run integration tests
run-name: Run integration tests
on:
  status:
  check_run:

jobs:
  deploy-to-integration:
    uses: ./.github/workflows/main.yml
    with:
      deployment_arguments: ...
    secrets: inherit