name: Run Snyk Checks
run-name: Run Snyk Checks
on:
  status:
  check_run:

jobs:
  deploy-to-integration:
    uses: ./.github/workflows/main.yml
    with:
      deployment_arguments: ...
    secrets: inherit